# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 16154034164f5faa35a5e66470980655b263056cd2d41cb49d1ddc79a9a95fec35e05e3bfabdf6c299964fbb81f061956d33e996ee87eb0cf090d23853899c6f

  googledrive:
    client_id: '194664296353-c0sdnrfulgf7ngo9orflfqmo9g6vhe00.apps.googleusercontent.com'
    client_secret: 'rCEMJ72oGKvRyLr55Ey5xa6K'

  dropbox:
    app_key: '7ui91ve6t74ugkq'
    app_secret: 'c1qbkaypvh8dmvc'

test:
  secret_key_base: b59fac16d3d5d8c4b75a424ae90fcc9f3810b275781cc7c466c0c62bd8098ac5fb1ba140f57e0cdd51466045b20659596a198aa6e4acc045ddf41565fcc209ed

  dropbox:
    app_key: 7ui91ve6t74ugkq
    app_secret: c1qbkaypvh8dmvc

  googledrive:
    client_id: '194664296353-c0sdnrfulgf7ngo9orflfqmo9g6vhe00.apps.googleusercontent.com'
    client_secret: 'rCEMJ72oGKvRyLr55Ey5xa6K'

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
